
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace oylesine.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Cinsiyetler
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Cinsiyetler()
    {

        this.Kullanicilars = new HashSet<Kullanicilar>();

    }


    public int CinsiyetID { get; set; }

    public string Cinsiyet { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Kullanicilar> Kullanicilars { get; set; }

}

}
