//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oylesine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gonderiler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gonderiler()
        {
            this.Begenilers = new HashSet<Begeniler>();
            this.Yorumlars = new HashSet<Yorumlar>();
        }
    
        public int GonderiID { get; set; }
        public int KullaniciID { get; set; }
        public string Icerik { get; set; }
        public Nullable<int> MedyaID { get; set; }
        public System.DateTime GonderiTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Begeniler> Begenilers { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual Medyalar Medyalar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yorumlar> Yorumlars { get; set; }
    }
}
