

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace oylesine.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class oylesineEntities : DbContext
{
    public oylesineEntities()
        : base("name=oylesineEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Arkadaslik> Arkadasliks { get; set; }

    public virtual DbSet<Begeniler> Begenilers { get; set; }

    public virtual DbSet<Cinsiyetler> Cinsiyetlers { get; set; }

    public virtual DbSet<Gonderiler> Gonderilers { get; set; }

    public virtual DbSet<Kullanicilar> Kullanicilars { get; set; }

    public virtual DbSet<Medyalar> Medyalars { get; set; }

    public virtual DbSet<sysdiagram> sysdiagrams { get; set; }

    public virtual DbSet<Yorumlar> Yorumlars { get; set; }

}

}

