//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oylesine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorum
    {
        public int YorumId { get; set; }
        public int GonderiId { get; set; }
        public int KullaniciId { get; set; }
        public string Icerik { get; set; }
    
        public virtual Gonderi Gonderi { get; set; }
        public virtual Kullanici Kullanici { get; set; }
    }
}
